services:
  - type: web
    name: hello-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
  - type: web
    name: hello-web
    runtime: static
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build:web
    staticPublishPath: ./dist
